[package]
name = "game-util"
version = "0.1.0"
authors = ["MinusKelvin <mark.carlson@minuskelvin.net>"]
edition = "2018"

[dependencies]
euclid = { version = "0.22", features = ["serde"] }
glow = "0.6"
glutin = { version = "0.25", features = ["serde"] }
rusttype = { version = "0.9", features = ["gpu_cache"] }
image = "0.23"
serde = { version = "1.0", features = ["derive"] }
arrayvec = "0.5"
rodio = "0.11.0"
scopeguard = "1.1"
