[package]
name = "game-util"
version = "0.1.0"
authors = ["MinusKelvin <mark.carlson@minuskelvin.net>"]
edition = "2018"

[dependencies]
lyon = "0.14.0"
euclid = { version = "0.20.1", features = ["serde"] }
gl = "0.13.0"
glutin = "0.21.0"
rusttype = { version = "0.7.7", features = ["gpu_cache"] }
image = "0.22.0"
serde = { version = "1.0.97", features = ["derive"] }
