[package]
name = "game-util"
version = "0.1.0"
authors = ["MinusKelvin <mark.carlson@minuskelvin.net>"]
edition = "2018"

[dependencies]
euclid = { version = "0.20.1", features = ["serde"] }
gl = "0.13.0"
glutin = { version = "0.21.0", features = ["serde"] }
rusttype = { version = "0.7.7", features = ["gpu_cache"] }
image = "0.23"
serde = { version = "1.0.97", features = ["derive"] }
arrayvec = "0.4.11"
rodio = "0.11.0"
